name: Build, Publish and Release
run-name: ${{ github.actor }} is building, publishing and releasing 
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  call-asset-build:
    if: github.event.pull_request.merged == true
    uses: luitjens-test-gh-app/workflows/.github/workflows/asset-build-and-publish.yml@349d585659e6af7c1f2b03bc13e0280850c4a456
    secrets: inherit
